# Image Python officielle
FROM python:3.11-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier requirements
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le code Flask
COPY . .

# Exposer le port Flask
EXPOSE 5000

# Lancer l'application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
